site_name: Semantic Technologies team at ZB MED
nav:
    - Home: index.md

# Repository
repo_name: zbmed-semtec/zbmed-semtec.github.io
repo_url: https://github.com/zbmed-semtec/zbmed-semtec.github.io

theme: readthedocs
