site_name: Semantic Technologies team at ZB MED
site_url: https://zbmed-semtec.github.io/
nav:
    - Home: index.md
    - Projects : 
      - OntoClue : projects/2021_OntoClue.md
      - maSMPs: projects/2022_maSMP.md
      - TREC doc2doc: projects/2022_TREC_doc2doc.md
    - Theses:
      - Protein function embeddings: theses/2023_Protein_function_embeddings.md  
    - Software: software.md
    - Vocabularies: vocabularies.md
    - Datasets: datasets.md
    - Consortia: 
      - STELLA Living Labs: consortia/2018_STELLA.md
      - NFDI4DataScience: consortia/2021_NFDI4DataScience.md
    - Current members: current_members.md
    - Previous members: previous_members.md
markdown_extensions:
  - toc:
      toc_depth: 3

# Repository
repo_name: zbmed-semtec/zbmed-semtec.github.io
repo_url: https://github.com/zbmed-semtec/zbmed-semtec.github.io

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: orange
    accent: orange
  logo: https://raw.githubusercontent.com/zbmed-semtec/zbmed-semtec.github.io/main/semtec.png
  extrahead:
  - |
    <script>
      function openHTMLPreview() {
        window.open('metadata/projects/ro-crate-preview.html', '_blank');
      }
    </script>
