site_name: Semantic Technologies team at ZB MED
nav:
    - Home: index.md
    - Projects : projects.md
    - Software: software.md
    - Vocabularies: vocabularies.md
    - Datasets: datasets.md
    - Current members: current_members.md
    - Previous members: previous_members.md
markdown_extensions:
  - toc:
      toc_depth: 3

# Repository
repo_name: zbmed-semtec/zbmed-semtec.github.io
repo_url: https://github.com/zbmed-semtec/zbmed-semtec.github.io

theme:
  name: material
  palette:
    primary: orange
    accent: orange
  logo: https://raw.githubusercontent.com/zbmed-semtec/zbmed-semtec.github.io/main/semtec.png
